export const metadata = { title: "Terms of Use | UK Calculator Platform" };

export default function TermsOfUse() {
  return (
    <div className="prose max-w-none">
      <h1>Terms of Use</h1>
      <p>Last updated: August 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing and using the UK Calculator Platform (the &quot;Service&quot;), operated by Jomovate, you accept and agree to be bound by these Terms of Use. If you do not agree to these Terms, you must not use the Service.
      </p>

      <h2>2. Use of the Service</h2>
      <p>
        The Service provides estimation tools and calculators for informational and illustrative purposes only. The outputs generated by the Service do not constitute financial, legal, tax, or professional advice. You should always consult with a qualified professional before making any financial or legal decisions.
      </p>

      <h2>3. Accuracy of Information</h2>
      <p>
        While we strive to ensure that the mathematical formulas and regulatory rulesets used in our calculators are accurate and up-to-date, we do not guarantee the accuracy, completeness, or reliability of any results. Rules, tax rates, and regulations change frequently.
      </p>
      <p>
        <strong>Currency Conversion:</strong> Exchange rates are provided on a best-effort basis using a third-party service (the Frankfurter API). These rates are for illustrative purposes and may not reflect the exact real-time market rates or the rates you would receive from a financial institution. We are not liable for any discrepancies in exchange rates.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, Jomovate and its affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with your use of, or inability to use, the Service or the results provided by the Service. 
      </p>

      <h2>5. Intellectual Property</h2>
      <p>
        The Service, including its code, design, and content, is the intellectual property of Jomovate and is protected by copyright and other intellectual property laws.
      </p>

      <h2>6. Modifications to the Service and Terms</h2>
      <p>
        We reserve the right to modify or discontinue the Service at any time without notice. We may also update these Terms of Use periodically. Continued use of the Service after changes indicates your acceptance of the new Terms.
      </p>

      <h2>7. Contact</h2>
      <p>
        For any questions regarding these Terms of Use, please contact <a href="mailto:dju78@jomovate.com">dju78@jomovate.com</a>.
      </p>
    </div>
  );
}
